# Generated by Django 4.1.5 on 2023-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.URLField(unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
