# Generated by Django 4.1.5 on 2023-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='time',
            new_name='created_at',
        ),
    ]
