# Generated by Django 4.1.5 on 2023-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_time_urls_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
