# Generated by Django 4.1.5 on 2023-02-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_urls_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='data',
            new_name='text',
        ),
    ]
